#!/bin/zsh
if [ `/usr/libexec/PlistBuddy -c "Print AppleSelectedInputSources:0:'Input Mode'" ~/Library/Preferences/com.apple.HIToolbox.plist` ];then; echo 'JP';else;echo 'US';fi

#!/usr/local/bin/fish
#function get-ime
#    if /usr/libexec/PlistBuddy -c "Print AppleSelectedInputSources:0:'Input Mode'" ~/Library/Preferences/com.apple.HIToolbox.plist|grep Japanese|echo $status
