#!/usr/local/bin/fish

#tmux
if ls ~/.tmux.conf > /dev/null 2>&1
	rm ~/.tmux.conf
end
ln -s ~/dotfile/tmux.conf ~/.tmux.conf
if [ $status -eq 1 ];false;end;exit


#.config/ check
if ls ~/.config > /dev/null 2>&1
else
	mkdir ~/.config
end
if [ $status -eq 1 ];false;end;exit


#fish
if ls ~/.config/fish > /dev/null 2>&1
	if ls ~/.config/fish/config.fish > /dev/null 2>&1
		rm ~/.config/fish/config.fish
	end
else
	mkdir ~/.config/fish
end
ln -s ~/dotfile/config.fish ~/.config/fish/
if [ $status -eq 1 ];false;end;exit


#nvim
if ls ~/.config/nvim > /dev/null 2>&1
	if ls ~/.config/nvim/init.vim > /dev/null 2>&1
		rm ~/.config/nvim/init.vim
	end
else
	mkdir ~/.config/nvim
end
ln -s ~/dotfile/init.vim ~/.config/nvim/
if [ $status -eq 1 ];false;end;exit
